### ISSUE TITLE
MoveIt! freezes when it uses tilt scan pointcloud

### ISSUE THREAD

**Issue by tarukosu** [moveit/moveit_core#212]
When I used MoveIt! for PR2 in gazebo, MoveIt! freezed and rviz didn't work well.
At that time, MoveIt! used pointcloud generated from tilt scan data.

This is yaml file for sensor configuration.

```
sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /tilt_scan_shadow_filtered
    max_range: 5.0
    padding_offset: 0.06
    padding_scale: 1.0
    filtered_cloud_topic: filtered_cloud
```

This is /tilt_scan_shadow_filtered bag file.
https://drive.google.com/file/d/0BzwRmQaIVeI0MDhPMzRUbmYwREU/view?usp=sharing

When MoveIt! used pointcloud generated from kinect data, it worked well.

![screenshot_from_2014-11-27 14 31 43](https://cloud.githubusercontent.com/assets/4415085/5212794/5cdcbdaa-7643-11e4-824d-1214ee457470.png)
